title: Bence Hamrák 
logo: https://media.licdn.com/dms/image/v2/D4D03AQHix7r26U55xg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1710517946274?e=1740614400&v=beta&t=X3sDSuFyMChEBO99o8e4DrLQs6Fiu-H12xSEG2JK6vs
description: > 
  <br>
  ✉️ <a href="mailto:hamrak_bence@phd.ceu.edu"> hamrak_bence@phd.ceu.edu </a> 
  <br>
  🦋 <a href="https://bsky.app/profile/benhmrk.bsky.social"> @benhmrk.bsky.social </a> 
  <br>
  🎓 <a href="https://scholar.google.com/citations?user=uOswV2gAAAAJ&hl=hu"> Google scholar </a>
  <br>
  💼 <a href="https://www.linkedin.com/in/bence-hamrak-b2010a133/"> LinkedIn </a>
  <br>
  📝 <a href=""> Cirruculum vitae </a>
theme: jekyll-theme-minimal
sass: 
  custom_css: /assets/css/style.scss
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
