theme: jekyll-theme-minimal
title: Bence Hamrak 
description: PhD candidate at CEU
logo: https://dsps.ceu.edu/sites/pds.ceu.hu/files/styles/panopoly_image_full/public/profilephd/portrait/1460/profile.jpg?itok=GsDjZKNG
show_downloads: false
layout: default
